/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tugasProject;

import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableColumnModel;
import javax.swing.table.DefaultTableModel;
import tugasProject.Guru;

/**
 *
 * @author ASUS
 */
public class GUI_pendataanGuru extends javax.swing.JFrame {

    /**
     * Creates new form pendataanGuru_GUI
     */
    public GUI_pendataanGuru() {
        initComponents();
        // Membuat objek Guru dengan data awal atau konstructor
        //        Guru data = new Guru("G5426", "Irfan", "Laki - laki", "Islam", "Sidoarjo", "085456123789", 5642314);
        //
        //        txtkodeGuru.setText(data.kodeGuru);
        //        txtNuptk.setText(Integer.toString(data.nuptk));
        //        txtNama.setText(data.nama);
        //        if (data.jenisKelamin.equals("Laki - laki")) {
        //            rdLaki.setSelected(true);
        //            rdPerempuan.setSelected(false);
        //        } else {
        //            rdLaki.setSelected(false);
        //            rdPerempuan.setSelected(true);
        //        }
        //        txtAgama.setText(data.agama);
        //        txtAlamat.setText(data.alamat);
        //        txtTelp.setText(data.noTelp);
        //        // Menampilkan status mengajar guru
        //        cbStatusMengajar.setSelected(true);
        //
        //        // Menonaktifkan elemen-elemen antarmuka pengguna agar tidak dapat diubah
        //        txtkodeGuru.setEnabled(false);
        //        txtNuptk.setEnabled(false);
        //        txtNama.setEnabled(false);
        //        rdLaki.setEnabled(false);
        //        rdPerempuan.setEnabled(false);
        //        txtAgama.setEnabled(false);
        //        txtAlamat.setEnabled(false);
        //        txtTelp.setEnabled(false);
        //        cbStatusMengajar.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnJk = new javax.swing.ButtonGroup();
        jOptionPane1 = new javax.swing.JOptionPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNuptk = new javax.swing.JTextField();
        rdLaki = new javax.swing.JRadioButton();
        rdPerempuan = new javax.swing.JRadioButton();
        txtNama = new javax.swing.JTextField();
        txtAgama = new javax.swing.JTextField();
        txtAlamat = new javax.swing.JTextField();
        txtTelp = new javax.swing.JTextField();
        btnProses = new javax.swing.JButton();
        btnTutup = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        cbStatusMengajar = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        txtkodeGuru = new javax.swing.JTextField();
        btnHapus = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_dataGuru = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(jLabel1.getFont().deriveFont(jLabel1.getFont().getStyle() | java.awt.Font.BOLD, jLabel1.getFont().getSize()+6));
        jLabel1.setText("PENDATAAN DATA GURU");

        jLabel2.setText("NUPTK");

        jLabel3.setText("Nama");

        jLabel4.setText("Alamat");

        jLabel5.setText("No. Telp");

        jLabel6.setText("Agama");

        jLabel7.setText("Jenis Kelamin");

        txtNuptk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNuptkActionPerformed(evt);
            }
        });

        btnJk.add(rdLaki);
        rdLaki.setText("Laki - Laki");

        btnJk.add(rdPerempuan);
        rdPerempuan.setText("Perempuan");

        txtTelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelpActionPerformed(evt);
            }
        });

        btnProses.setText("Simpan");
        btnProses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProsesActionPerformed(evt);
            }
        });

        btnTutup.setText("Tutup");
        btnTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTutupActionPerformed(evt);
            }
        });

        jLabel8.setText("Satus");

        cbStatusMengajar.setText("Sedang Mengajar");

        jLabel9.setText("Kode Guru");

        txtkodeGuru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkodeGuruActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        table_dataGuru.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NUPTK", "Kode Guru", "Nama", "Jenis Kelamin", "Agama", "Alamat", "No. Telp", "Email", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table_dataGuru);

        jLabel10.setText("Email");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(276, 276, 276)
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(rdLaki, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rdPerempuan, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNama)
                                    .addComponent(txtAgama)
                                    .addComponent(txtTelp)
                                    .addComponent(txtAlamat)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel2))
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtNuptk, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtkodeGuru, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel10)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbStatusMengajar)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnProses)
                .addGap(45, 45, 45)
                .addComponent(btnHapus)
                .addGap(41, 41, 41)
                .addComponent(btnBatal)
                .addGap(44, 44, 44)
                .addComponent(btnTutup)
                .addGap(106, 106, 106))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNuptk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtkodeGuru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(rdLaki))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdPerempuan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtAgama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtTelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbStatusMengajar)
                            .addComponent(jLabel8)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHapus)
                    .addComponent(btnBatal)
                    .addComponent(btnTutup)
                    .addComponent(btnProses))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProsesActionPerformed
        // TODO add your handling code here:
        // Mendapatkan data inputan
//        String kodeGuru = txtkodeGuru.getText();
//        String nuptk = txtNuptk.getText();
//        String nama = txtNama.getText();
//        String jenisKelamin = rdLaki.isSelected() ? "Laki - laki" : "Perempuan";
//        String agama = txtAgama.getText();
//        String alamat = txtAlamat.getText();
//        String noTelp = txtTelp.getText();
//
//        // Mengecek status mengajar berdasarkan checkbox
//        String statusMengajar = cbStatusMengajar.isSelected() ? "Sedang Mengajar" : "Tidak Mengajar";
//
        // Menyusun data inputan dan status mengajar menjadi string
//        String data = "DATA GURU SEKOLAH\n";
//        data += "================================\n";
//        data += "NUPTK \t: " + nuptk + "\n";
//        data += "Kode Guru \t: " + kodeGuru + "\n";
//        data += "Nama \t: " + nama + "\n";
//        data += "Jenis Kelamin \t: " + jenisKelamin + "\n";
//        data += "Agama \t: " + agama + "\n";
//        data += "Alamat \t: " + alamat + "\n";
//        data += "No Telp \t: " + noTelp + "\n";
//        data += "--------------------------------------------------------\n";
//        data += "Status Mengajar: " + statusMengajar + "\n";
//
//        // Menampilkan data inputan ke memo
//        memo.setText(data);

        // Mengambil model data dari tabel
        DefaultTableModel dataModel = (DefaultTableModel) table_dataGuru.getModel();

        // Inisialisasi sebuah ArrayList bernama 'list'
        List<Object> list = new ArrayList<>();

        // Mengatur tabel untuk membuat kolom dari model secara otomatis 
        table_dataGuru.setAutoCreateColumnsFromModel(true);

        // Inisialisasi variabel jenisKelamin
        String jenisKelamin = "";

        // Membuat instance dari kelas Guru
        Guru guru = new Guru("", "", "Laki-Laki", "", "", "", 0, "");

        // Mengatur data kode guru menggunakan nilai dari komponen
        guru.setKodeGuru(txtkodeGuru.getText());

        // Mengatur data nama menggunakan nilai dari komponen
        guru.setNama(txtNama.getText());

        // Mengatur jenis kelamin sesuai dengan radio button yang dipilih
        if (rdLaki.isSelected()) {
            jenisKelamin = rdLaki.getText();
        } else {
            jenisKelamin = rdPerempuan.getText();
        }
        guru.setJenisKelamin(jenisKelamin);

        // Mengatur data agama menggunakan nilai dari komponen
        guru.setAgama(txtAgama.getText());

        // Mengatur data alamat menggunakan nilai dari komponen
        guru.setAlamat(txtAlamat.getText());

        // Mengatur data nomor telepon menggunakan nilai dari komponen
        guru.setNoTelp(txtTelp.getText());
        
        guru.setEmail(txtEmail.getText());

        // Mengatur data NUPTK menggunakan nilai dari komponen
        guru.setNuptk(Integer.parseInt(txtNuptk.getText()));

        // Mengatur status mengajar menggunakan nilai dari checkbox
        guru.setStatusMengajar(cbStatusMengajar.isSelected());

        // Menambahkan data-data dari objek Guru ke dalam ArrayList 'list'
        list.add(guru.getNuptk());
        list.add(guru.getKodeGuru());
        list.add(guru.getNama());
        list.add(guru.getJenisKelamin());
        list.add(guru.getAgama());
        list.add(guru.getAlamat());
        list.add(guru.getNoTelp());
        list.add(guru.getEmail());
        list.add(guru.isStatusMengajar());

        // Menambahkan baris baru ke model tabel menggunakan data dari ArrayList 'list'
        dataModel.addRow(list.toArray());

        // Memanggil fungsi 'clear' untuk membersihkan nilai dari komponen
        clear();
    }//GEN-LAST:event_btnProsesActionPerformed

    private void btnTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTutupActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnTutupActionPerformed

    private void txtNuptkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNuptkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNuptkActionPerformed

    private void txtTelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelpActionPerformed

    private void txtkodeGuruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkodeGuruActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtkodeGuruActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        // Mengambil model data dari tabel
        DefaultTableModel dataModel = (DefaultTableModel) table_dataGuru.getModel();

        // Mendapatkan indeks baris yang dipilih
        int selectedRow = table_dataGuru.getSelectedRow();

        // Memastikan ada baris yang dipilih sebelum menghapus
        if (selectedRow != -1) {
            // Menghapus baris yang dipilih dari model tabel
            dataModel.removeRow(selectedRow);
        } else {
            // Jika tidak ada baris yang dipilih, berikan pesan atau lakukan tindakan lain
            jOptionPane1.showMessageDialog(this, "Pilih baris yang ingin dihapus.", "Peringatan", jOptionPane1.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_btnBatalActionPerformed

    //untuk membatalkan pengisian data
    public void clear() {
        txtNuptk.setText("");
        txtkodeGuru.setText("");
        txtNama.setText("");
        txtAgama.setText("");
        txtAlamat.setText("");
        txtTelp.setText("");
        txtEmail.setText("");
        btnJk.clearSelection();
        cbStatusMengajar.setSelected(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_pendataanGuru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_pendataanGuru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_pendataanGuru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_pendataanGuru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_pendataanGuru().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnHapus;
    private javax.swing.ButtonGroup btnJk;
    private javax.swing.JButton btnProses;
    private javax.swing.JButton btnTutup;
    private javax.swing.JCheckBox cbStatusMengajar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdLaki;
    private javax.swing.JRadioButton rdPerempuan;
    private javax.swing.JTable table_dataGuru;
    private javax.swing.JTextField txtAgama;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNuptk;
    private javax.swing.JTextField txtTelp;
    private javax.swing.JTextField txtkodeGuru;
    // End of variables declaration//GEN-END:variables
}
